[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
rustflags = ["-C", "default-linker-libraries"]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults;sdkconfig.defaults.esp32c3", relative = true }